src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
// use Doctrine\Common\Collections\ArrayCollection;
// use Doctrine\Common\Collections\Collection;
// use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use ApiPlatform\Core\Annotation\ApiResource;

/**
 * @ApiResource
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=15)
     */
    private $role;

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phone_office;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phone_mobile;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $street1;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $street2 = null;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $postcode;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=25, nullable=true)
     */
    private $status;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $profile_pic;

    /**
     * @ORM\Column(type="string", length=60, nullable=true)
     */
    private $country;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $birthDate;

    /**
     * @ORM\Column(type="string", length=47, nullable=true)
     */
    private $activationKey;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     * Civilité : Mr Mme Dr Pr... podolff ?
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=80, nullable=true)
     */
    private $profession;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $bio;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $socid;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $timezone;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $alias;

    public function __construct()
    {
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRole(): string
    {

        return (string) $this->role;
    }

    public function setRole(string $role): self
    {
        $this->role = $role;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(?string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getPhoneOffice(): ?string
    {
        return $this->phone_office;
    }

    public function setPhoneOffice(?string $phone_office): self
    {
        $this->phone_office = $phone_office;

        return $this;
    }

    public function getPhoneMobile(): ?string
    {
        return $this->phone_mobile;
    }

    public function setPhoneMobile(?string $phone_mobile): self
    {
        $this->phone_mobile = $phone_mobile;

        return $this;
    }

    public function getStreet1(): ?string
    {
        return $this->street1;
    }

    public function setStreet1(?string $street1): self
    {
        $this->street1 = $street1;

        return $this;
    }

    public function getStreet2(): ?string
    {
        return $this->street2;
    }

    public function setStreet2(?string $street2): self
    {
        $this->street2 = $street2;

        return $this;
    }

    public function getPostcode(): ?string
    {
        return $this->postcode;
    }

    public function setPostcode(string $postcode): self
    {
        $this->postcode = $postcode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    /**
     * liste : valid, pending, suspended, disabled
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getProfilePic(): ?string
    {
        return $this->profile_pic;
    }

    public function setProfilePic(?string $profile_pic): self
    {
        $this->profile_pic = $profile_pic;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birthDate;
    }

    public function setBirthDate(?\DateTime $birthDate): self
    {
        $this->birthDate = $birthDate;

        return $this;
    }

    public function getActivationKey(): ?string
    {
        return $this->activationKey;
    }

    public function setActivationKey(?string $activationKey): self
    {
        $this->activationKey = $activationKey;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getProfession(): ?string
    {
        return $this->profession;
    }

    public function setProfession(?string $profession): self
    {
        $this->profession = $profession;

        return $this;
    }

    public function getBio(): ?string
    {
        return $this->bio;
    }

    public function setBio(?string $bio): self
    {
        $this->bio = $bio;

        return $this;
    }

    public function getSocid(): ?int
    {
        return $this->socid;
    }

    public function setSocid(?int $socid): self
    {
        $this->socid = $socid;

        return $this;
    }

    public function getRoles()
    {
        # code...
    }

    public function getTimezone(): ?string
    {
        return $this->timezone;
    }

    public function setTimezone(string $timezone): self
    {
        $this->timezone = $timezone;

        return $this;
    }

    public function getAlias(): ?string
    {
        return $this->alias;
    }

    public function setAlias(string $alias): self
    {
        $this->alias = $alias;

        return $this;
    }

    public function generate($length)
    {
        $list = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ$&@!.-_%;:,?=+';
        $chaine = '';
        $max = mb_strlen($list) - 1;
        for ($i = 0; $i < $length; $i++) {
            $chaine .= $list[random_int(0, $max)];
        }

        return $chaine;
    }

    public function generateKey($length)
    {
        $list = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
        $chaine = '';
        $max = mb_strlen($list) - 1;
        for ($i = 0; $i < $length; $i++) {
            $chaine .= $list[random_int(0, $max)];
        }

        return $chaine;
    }

    public function getSlug()
    {
        $slug = '';
        if ($this->title == 'Dr' | $this->title == 'Pr') {
            $slug = $this->title . ' ';
        }
        $slug .= $this->first_name . ' ' . $this->name . ' (' . $this->alias . ')';
        return $slug;
    }
}

templates/ado/audiobooks.html.twig
{% extends "ado/navbar.html.twig" %}

{% block title %}
	Capsule - Audiobooks
{% endblock %}

{% block body %}
	<h1>Tes audiobooks</h1>

	<div class="col" style="margin: 100px">
		<a href="/ado/home" role="button" class="btn btn-dark">Retour à l'accueil</a>
	</div>
{% endblock %}

templates/ado/community.html.twig
{% extends "ado/navbar.html.twig" %}

{% block title %}
	Capsule - Communauté
{% endblock %}

{% block body %}
	<h1>Ma communauté</h1>

	<i>** Coming soon **</i>

	<div class="col" style="margin: 100px">
		<a href="/ado/home" role="button" class="btn btn-dark">Retour à l'accueil</a>
	</div>
{% endblock %}

templates/ado/family.html.twig
{% extends "ado/navbar.html.twig" %}

{% block title %}
	Capsule - Famille
{% endblock %}

{% block body %}
	<h1>Espace famille</h1>

	<i>** Coming soon **</i>

	<div class="col" style="margin: 100px">
		<a href="/ado/home" role="button" class="btn btn-dark">Retour à l'accueil</a>
	</div>
{% endblock %}

templates/ado/home.html.twig
{% extends "base-js.html.twig" %}

{% block body %}
	<div class="container text-center">
		<div class="row" style="padding: 50px">
			<div class="col col-3">
				<p><img src="/{{ user.profilePic}}" alt="Photo de profil" style="height: 20vw; max-height: 200px; width: auto"></p>
			</div>
			<div class="col col-9" style="text-align: left">
				<h1>Salut
					{{ user.firstName }}</h1>
				<p>Bienvenue dans ton profil privé Capsule !
					<br>Comment vas-tu ? C'est quoi le plan aujourd'hui ?
					<br>** Idée : plusieurs textes accueil aléatoires **</p>
			</div>
		</div>
		<div class="row row-cols-1 row-cols-md-5">
			<div class="col" style="padding: 0 1vw; margin-bottom: 2vw">
				<div class="adoHome" style="background: rgba(127,217,208, 1);">
					<a href="/ado/notes"><img src="/images/ado_notes.jpg" alt="post it" style="width: 80%; height: auto; border-radius: 25px"></a>
					<p class="adoHome" style="margin: 1vw 0 0 0">
						<a class="adoHome" href="/ado/notes">Tes notes</a>
					</p>
				</div>
			</div>
			<div class="col" style="padding: 0 1vw; margin-bottom: 2vw">
				<div class="adoHome" style="background: rgba(127,217,208, 0.8);">
					<img src="/images/62daf98d587b549878220ab20213db8d.jpg" alt="Ton journal" style="width: 80%; height: auto; border-radius: 25px" title="Coming soon">
					<p class="adoHome" style="margin: 1vw 0 0 0">
						<a class="adoHome" href="/ado/agenda">Espace famille</a>
					</p>
				</div>
			</div>
			<div class="col" style="padding: 0 1vw; margin-bottom: 2vw">
				<div class="adoHome" style="background: rgba(127,217,208, 0.6);">
					<a href="/ado/journal"><img src="/images/ado_journal.jpg" alt="post it" style="width: 80%; height: auto; border-radius: 25px"></a>
					<p class="adoHome" style="margin: 1vw 0 0 0">
						<a class="adoHome" href="/ado/journal">Ton journal</a>
					</p>
				</div>
			</div>
			<div class="col" style="padding: 0 1vw; margin-bottom: 2vw">
				<div class="adoHome" style="background: rgba(127,217,208, 0.4);">
					<a href="/ado/agenda"><img src="/images/ado_agenda.jpg" alt="post it" style="width: 80%; height: auto; border-radius: 25px"></a>
					<p class="adoHome" style="margin: 1vw 0 0 0">
						<a class="adoHome" href="/ado/agenda">Ton agenda</a>
					</p>
				</div>
			</div>
			<div class="col" style="padding: 0 1vw; margin-bottom: 2vw">
				<div class="adoHome" style="background: rgba(127,217,208, 0.2);">
					<a href="/ado/messages"><img src="/images/ado_messages.jpg" alt="post it" style="width: 80%; height: auto; border-radius: 25px"></a>
					<p class="adoHome" style="margin: 1vw 0 0 0">
						<a class="adoHome" href="/ado/messages">Tes messages</a>
					</p>
				</div>
			</div>
			<div class="col" style="padding: 0 1vw; margin-bottom: 2vw">
				<div class="adoHome" style="background: rgba(127,217,208, 1);">
					<a href="/ado/audiobooks"><img src="/images/ado_audiobooks.jpg" alt="post it" style="width: 80%; height: auto; border-radius: 25px"></a>
					<p class="adoHome" style="margin: 1vw 0 0 0">
						<a class="adoHome" href="/ado/audiobooks">Tes audiobooks</a>
					</p>
				</div>
			</div>
			<div class="col" style="padding: 0 1vw; margin-bottom: 2vw">
				<div class="adoHome" style="background: rgba(127,217,208, 0.8);">
					<img src="/images/ado_videos.jpg" alt="Ton journal" style="width: 80%; height: auto; border-radius: 25px" title="Coming soon">
					<p class="adoHome" style="margin: 1vw 0 0 0">
						<a class="adoHome" href="/ado/videos">Tes vidéos</a>
					</p>
				</div>
			</div>
			<div class="col" style="padding: 0 1vw; margin-bottom: 2vw">
				<div class="adoHome" style="background: rgba(127,217,208, 0.6);">
					<a href="/ado/podcasts"><img src="/images/ado_podcasts.jpg" alt="post it" style="width: 80%; height: auto; border-radius: 25px"></a>
					<p class="adoHome" style="margin: 1vw 0 0 0">
						<a class="adoHome" href="/ado/podcasts">Tes podcasts</a>
					</p>
				</div>
			</div>
			<div class="col" style="padding: 0 1vw; margin-bottom: 2vw">
				<div class="adoHome" style="background: rgba(127,217,208, 0.4);">
					<a href="/ado/news"><img src="/images/ado_news.jpg" alt="post it" style="width: 80%; height: auto; border-radius: 25px"></a>
					<p class="adoHome" style="margin: 1vw 0 0 0">
						<a class="adoHome" href="/ado/news">Les news</a>
					</p>
				</div>
			</div>
			<div class="col" style="padding: 0 1vw; margin-bottom: 2vw">
				<div class="adoHome" style="background: rgba(127,217,208, 0.2);">
					<a href="/ado/community"><img src="/images/ado_community.jpg" alt="post it" style="width: 80%; height: auto; border-radius: 25px"></a>
					<p class="adoHome" style="margin: 1vw 0 0 0">
						<a class="adoHome" href="/ado/community">Communauté</a>
					</p>
				</div>
			</div>
		</div>

		{# Ressources #}
		{#
		<div class="row" style="padding: 75px">
			<div>
				<img src="/images/landing_ressources.png" alt="landing_ressources.png" style="margin-bottom: 25px; max-width:400px; width:100vw"><br>
			</div>

			<h5>VIDEOS</h5>
			<div class="row row-cols-1 row-cols-md-3 mb-3">
				<div class="col">
					<iframe style="width:75vw; max-width:300px; height:75vw; max-height:300px" border-radius="20%" src="https://www.youtube.com/embed/k17Ul2eTzus" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
				</div>
				<div class="col">
					<iframe style="width:75vw; max-width:300px; height:75vw; max-height:300px" src="https://www.youtube.com/embed/eqCyYR_bGDE?controls=0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
				</div>
				<div class="col">
					<iframe style="width:75vw; max-width:300px; height:75vw; max-height:300px" src="https://www.youtube.com/embed/GPPK-qqtmCU?controls=0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
				</div>
			</div>

			<h5>PODCASTS</h5>
			<div class="row row-cols-1 row-cols-md-3 mb-3">
				<div class="col">
					<img src="/images/landing_podcast.png" style="border-radius: 50%; max-height:250px; max-width:250px" alt="landing_podcast.png">
					<br>Podcast 1
				</div>
				<div class="col">
					<img src="/images/landing_podcast.png" style="border-radius: 50%; max-height:250px; max-width:250px" alt="landing_podcast.png">
					<br>Podcast 2
				</div>
				<div class="col">
					<img src="/images/landing_podcast.png" style="border-radius: 50%; max-height:250px; max-width:250px" alt="landing_podcast.png">
					<br>Podcast 3
				</div>
			</div>

			<h5>AUDIOBOOKS</h5>
			<div class="row row-cols-1 row-cols-md-3 mb-3">
				<div class="col">
					<img src="/images/landing_audiobooks.png" style="border-radius: 50%; max-height:250px; max-width:250px" alt="landing_podcast.png">
					<br>Livre audio 1
				</div>
				<div class="col">
					<img src="/images/landing_audiobooks.png" style="border-radius: 50%; max-height:250px; max-width:250px" alt="landing_podcast.png">
					<br>Livre audio 2
				</div>
				<div class="col">
					<img src="/images/landing_audiobooks.png" style="border-radius: 50%; max-height:250px; max-width:250px" alt="landing_podcast.png">
					<br>Livre audio 3
				</div>
			</div>

		</div>
		#}
	</div>


{% endblock %}

templates/ado/journal.html.twig
{% extends "ado/navbar.html.twig" %}

{% block title %}
	Capsule - Journal
{% endblock %}

{% block body %}
	<h1>Ton journal</h1>

	<div class="col" style="margin: 100px">
		<a href="/ado/home" role="button" class="btn btn-dark">Retour à l'accueil</a>
	</div>
{% endblock %}

templates/ado/messages.html.twig
{% extends "base-js.html.twig" %}

{% block title %}
	Capsule - Messages
{% endblock %}

{% block body %}
	<div class="mx-auto py-8 px-10">
		<div {{ react_component('App', { userObj: userJson, userRole: role }) }}></div>
	</div>
{% endblock %}

templates/ado/navbar.html.twig
{% extends "base.html.twig" %}
{% block title %}
	Capsule - Jeune
{% endblock %}

{% block navbar %}

	{# barre de navigation #}
	<div class="navbar sticky-top" style="padding-top: 0;">
		<div class="container-fluid" style="background: rgb(127,217,208);">
			<a class="navbar-brand" href="/ado/home"><img src="/images/Logo.png" alt="Logo Capsule" width="40" height="48.2"></a>
			<a href="/ado/agenda" style="color:black; text-decoration:none">Mon agenda</a>
			<span style="color:grey; text-decoration:none" title="Coming soon">News</span>
			<a href="/ado/videos" style="color:black; text-decoration:none">Ressources</a>
			<a href="/ado/messages" style="color:black; text-decoration:none">Messages</a>
			<a data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample"><img src="/images/user40.png" alt="Profil utilisateur"></a>
		</div>
	</div>
{% endblock %}

{% block body %}{% endblock %}

templates/ado/news.html.twig
{% extends "ado/navbar.html.twig" %}

{% block title %}
	Capsule - News
{% endblock %}

{% block body %}
	<h1>Ton news</h1>

	<div class="col" style="margin: 100px">
		<a href="/ado/home" role="button" class="btn btn-dark">Retour à l'accueil</a>
	</div>
{% endblock %}

templates/ado/notes.html.twig
{% extends "ado/navbar.html.twig" %}

{% block title %}
	Capsule - Notes
{% endblock %}

{% block body %}
	<h1>Tes notes</h1>

	<div class="col" style="margin: 100px">
		<a href="/ado/home" role="button" class="btn btn-dark">Retour à l'accueil</a>
	</div>
{% endblock %}

templates/ado/podcasts.html.twig
{% extends "ado/navbar.html.twig" %}

{% block title %}
	Capsule - Podcasts
{% endblock %}

{% block body %}
	<h1>Ton podcasts</h1>

	<div class="col" style="margin: 100px">
		<a href="/ado/home" role="button" class="btn btn-dark">Retour à l'accueil</a>
	</div>
{% endblock %}

templates/ado/profil.html.twig
{% extends "base-js.html.twig" %}

{% block title %}
	Capsule - Profil
{% endblock %}

{% block body %}

	<div class="container" style="margin-bottom: 30px">
		<h1 style="margin: 25px 0">{{user.title}}
			{{ user.firstName}}
			{{ user.name}}</h1>


		<div class="row" style="padding: 15px 0">
			<button class="btn btn-dark" style="width: 200px; margin: auto; background: white; color: black; border: 1px solid rgb(127,217,208)" onclick="reveal('infos')">Infos</button>
			<button class="btn btn-dark" style="width: 200px; margin: auto; background: white; color: black; border: 1px solid rgb(127,217,208)" onclick="reveal('interest')">Centres d'intérêts</button>
			<button class="btn btn-dark" style="width: 200px; margin: auto; background: white; color: black; border: 1px solid rgb(127,217,208)" onclick="reveal('family')">Famille</button>
			<button class="btn btn-dark" style="width: 200px; margin: auto; background: white; color: black; border: 1px solid rgb(127,217,208)" onclick="reveal('payments')">Paiements</button>
		</div>
		<div class="row" id="infos" style"display: block; margin: 15px 0">
			<div class="row">
				<div class="col-3">
					<p><img src="/{{user.profilePic}}" alt="Photo de profil" style="height: 20vw; max-height: 200px; width: auto"></p>
				</div>
				<div class="col">
					<table class="profile">
						<tr>
							<td class="label">Adresse&nbsp;:</td>
							<td class="value">{{user.street1}}<br>
								{{user.street2}}<br>
								{{user.postcode}}
								{{user.city}}<br>
								{{user.country}}</td>
						</tr>
						<tr>
							<td class="label">Email&nbsp;:</td>
							<td class="value">{{ user.email }}</td>
						</tr>
						<tr>
							<td class="label">Bureau&nbsp;:</td>
							<td class="value">{{ user.phoneOffice }}</td>
						</tr>
						<tr>
							<td class="label">Portable&nbsp;:</td>
							<td class="value">{{ user.phoneOffice }}</td>
						</tr>
						<tr>
							<td class="label">Compte&nbsp;:</td>
							<td class="value">{{user.role}}</td>
						</tr>
						<tr>
							<td class="label">Date&nbsp;de&nbsp;naissance&nbsp;:</td>
							<td class="value">
								{% if user.birthDate %}
									{{user.birthDate|date("d/m/Y")}}
								{% endif %}
							</td>
						</tr>
					</table>
				</div>
			</div>
		</div>
		<div class="row" id="interest" style="display: none; margin: 15px 0">Interest</div>
		<div class="row" id="family" style="display: none; margin: 15px 0">family</div>
		<div class="row" id="payments" style="display: none; margin: 15px 0">Paiements</div>
	</div>
{% endblock %}
{% block script %}
	<script>
		function reveal(div) {
let d1 = document.getElementById("infos");
let d2 = document.getElementById("interest");
let d3 = document.getElementById("family");
let d4 = document.getElementById("payments");
d1.style.display = "none";
d2.style.display = "none";
d3.style.display = "none";
d4.style.display = "none";
let d = document.getElementById(div);
d.style.display = "block";
}
	</script>
{% endblock %}
{% block admin %}
	<div style="margin-top: 50px">{{dump(user)}}</div>
{% endblock %}

templates/ado/timing.html.twig
{% extends "ado/navbar.html.twig" %}

{% block title %}
	Capsule - Timing
{% endblock %}

{% block body %}
	<h1>Prochain rdv dans</h1>

	<i>** idée : laisser la possibilité au jeune de créer son propre décompte, pour un événement qui lui tient à coeur **<br>
		** idée : pouvoir (mais pas obligatoire) le partager avec le praticien, le créer 'en live' pendant une visio **</i>


	<div class="col" style="margin: 100px">
		<a href="/ado/home" role="button" class="btn btn-dark">Retour à l'accueil</a>
	</div>
{% endblock %}

templates/ado/visio.html.twig
{% extends "ado/navbar.html.twig" %}

{% block title %}
	Capsule - Visio
{% endblock %}

{% block body %}
	<h1>Page d'accès à la visio</h1>

	<div class="col" style="margin: 100px">
		<a href="/ado/home" role="button" class="btn btn-dark">Retour à l'accueil</a>
	</div>
{% endblock %}