src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
// use Doctrine\Common\Collections\ArrayCollection;
// use Doctrine\Common\Collections\Collection;
// use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use ApiPlatform\Core\Annotation\ApiResource;

/**
 * @ApiResource
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=15)
     */
    private $role;

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phone_office;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phone_mobile;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $street1;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $street2 = null;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $postcode;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=25, nullable=true)
     */
    private $status;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $profile_pic;

    /**
     * @ORM\Column(type="string", length=60, nullable=true)
     */
    private $country;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $birthDate;

    /**
     * @ORM\Column(type="string", length=47, nullable=true)
     */
    private $activationKey;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     * Civilité : Mr Mme Dr Pr... podolff ?
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=80, nullable=true)
     */
    private $profession;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $bio;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $socid;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $timezone;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $alias;

    public function __construct()
    {
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRole(): string
    {

        return (string) $this->role;
    }

    public function setRole(string $role): self
    {
        $this->role = $role;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(?string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getPhoneOffice(): ?string
    {
        return $this->phone_office;
    }

    public function setPhoneOffice(?string $phone_office): self
    {
        $this->phone_office = $phone_office;

        return $this;
    }

    public function getPhoneMobile(): ?string
    {
        return $this->phone_mobile;
    }

    public function setPhoneMobile(?string $phone_mobile): self
    {
        $this->phone_mobile = $phone_mobile;

        return $this;
    }

    public function getStreet1(): ?string
    {
        return $this->street1;
    }

    public function setStreet1(?string $street1): self
    {
        $this->street1 = $street1;

        return $this;
    }

    public function getStreet2(): ?string
    {
        return $this->street2;
    }

    public function setStreet2(?string $street2): self
    {
        $this->street2 = $street2;

        return $this;
    }

    public function getPostcode(): ?string
    {
        return $this->postcode;
    }

    public function setPostcode(string $postcode): self
    {
        $this->postcode = $postcode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    /**
     * liste : valid, pending, suspended, disabled
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getProfilePic(): ?string
    {
        return $this->profile_pic;
    }

    public function setProfilePic(?string $profile_pic): self
    {
        $this->profile_pic = $profile_pic;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birthDate;
    }

    public function setBirthDate(?\DateTime $birthDate): self
    {
        $this->birthDate = $birthDate;

        return $this;
    }

    public function getActivationKey(): ?string
    {
        return $this->activationKey;
    }

    public function setActivationKey(?string $activationKey): self
    {
        $this->activationKey = $activationKey;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getProfession(): ?string
    {
        return $this->profession;
    }

    public function setProfession(?string $profession): self
    {
        $this->profession = $profession;

        return $this;
    }

    public function getBio(): ?string
    {
        return $this->bio;
    }

    public function setBio(?string $bio): self
    {
        $this->bio = $bio;

        return $this;
    }

    public function getSocid(): ?int
    {
        return $this->socid;
    }

    public function setSocid(?int $socid): self
    {
        $this->socid = $socid;

        return $this;
    }

    public function getRoles()
    {
        # code...
    }

    public function getTimezone(): ?string
    {
        return $this->timezone;
    }

    public function setTimezone(string $timezone): self
    {
        $this->timezone = $timezone;

        return $this;
    }

    public function getAlias(): ?string
    {
        return $this->alias;
    }

    public function setAlias(string $alias): self
    {
        $this->alias = $alias;

        return $this;
    }

    public function generate($length)
    {
        $list = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ$&@!.-_%;:,?=+';
        $chaine = '';
        $max = mb_strlen($list) - 1;
        for ($i = 0; $i < $length; $i++) {
            $chaine .= $list[random_int(0, $max)];
        }

        return $chaine;
    }

    public function generateKey($length)
    {
        $list = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
        $chaine = '';
        $max = mb_strlen($list) - 1;
        for ($i = 0; $i < $length; $i++) {
            $chaine .= $list[random_int(0, $max)];
        }

        return $chaine;
    }

    public function getSlug()
    {
        $slug = '';
        if ($this->title == 'Dr' | $this->title == 'Pr') {
            $slug = $this->title . ' ';
        }
        $slug .= $this->first_name . ' ' . $this->name . ' (' . $this->alias . ')';
        return $slug;
    }
}

templates/pro/home.html.twig
{% extends "base-js.html.twig" %}

{% block body %}
	<div class="container text-center" style="margin-top: 2vh;">
		<div class="row align-items-center" style="margin-bottom: 20px">
			<div class="col-3" style="max-width: 296.75px">
				<img src="{{user.profilePic}}" alt="Image de profil" style="width: 100%; max-width: 200px; height: auto">
			</div>
			<div class="col">
				<h1>Bonjour
					{{ user.firstName}}</h1>
				<p style="font-size: large">Bienvenue dans votre espace privé Capsule ! Comment allez-vous aujourd'hui ?</p>
			</div>
		</div>
		
		<div class="row row-cols-4" style="position: relative; z-index: -10">
			<div class="col">
				{# Pavé profil #}
				<div class="pave" style="margin-top: 45px; background-color: #e2e2e2; height: 150px">
					<div style="text-align: right; width: 100%; padding-right: 0.5vw; padding-top: 0.5vw">
						<a href="/pro/profil" class="btn"><img src="/images/add_green.png" alt="+" height="25vw"></a>
					</div>
					<img src="/images/pro_geometric_id.png" class="" alt="Image déco" style="border-radius: 50%; border: 5px solid white; height: 100px; width:100px; margin: -120px auto 0 auto">
					<div class="card-body">
						<h4 class="card-title" style="padding: 25px 0; font-weight: bold"> {# {{user.firstName}} #}
							{# {{user.name}}</h5> #}
					</div>
				</div>

				{# Pavé facturation #}
				<div class="pave" style="background-color: #03989e; color: white; height: 300px">
					<div style="position: absolute; bottom: 0; padding-left: 1vw; padding-bottom: 0.75vw; color:white; font-size: x-large; text-align: left">
						Espace facturation<br>
						<a href="/pro/repays"><img src="/images/left_arrow.png" alt="flèche droite" style="max-width: 40px; height: auto"></a>
					</div>
				</div>

			</div>
			<div class="col">

				{# Pavé patients #}
				<div class="pave" style="background-color: #99d9d9; margin-top: 45px; height: 200px;">
					<div style="text-align: right; width: 100%; padding-right: 0.5vw; padding-top: 0.5vw">
						<a href="/pro/patients" class="btn"><img src="/images/add_white.png" alt="+" height="25vw"></a>
					</div>
					<div style="position: absolute; bottom: 0; padding-left: 1vw; padding-bottom: 0.75vw; color:white; font-size: x-large">Patients</div>
				</div>

				{# Pavé nloc note #}
				<div class="pave" style="background-color: #e2e2e2; height: 250px">
					<div style="text-align: right; width: 100%; padding-right: 0.5vw; padding-top: 0.5vw">
						<a href="" class="btn"><img src="/images/add_red.png" alt="+" height="25vw"></a>
					</div>
					<div style="position: absolute; bottom: 0; padding-left: 1vw; padding-bottom: 0.75vw; font-size: x-large">Bloc note</div>
				</div>
			</div>
			<div class="col">

				{# Pavé calendrier #}
				<div class="pave" style="background-color: #e2e2e2; margin-top: 45px; height: 200px">
					<div style="text-align: right; width: 100%; padding-right: 0.5vw; padding-top: 0.5vw">
						<a href="" class="btn"><img src="/images/add_green.png" alt="+" height="25vw"></a>
					</div>
					<div style="position: absolute; bottom: 0; padding-left: 1vw; padding-bottom: 0.75vw; font-size: x-large">Calendrier</div>
				</div>

				{# Pavé CapsuleTV #}
				<div class="pave" style="background-color: #aa02ff; height: 250px">
					<div style="text-align: right; width: 100%; padding-right: 0.5vw; padding-top: 0.5vw">
						<a href="" class="btn"><img src="/images/add_white.png" alt="+" height="25vw"></a>
					</div>
					<div style="position: absolute; bottom: 0; padding-left: 1vw; padding-bottom: 0.75vw; color:white; font-size: x-large">Capsule TV</div>
				</div>
			</div>
			<div class="col">
				<div class="pave" style="background-color: #fa0644; margin-top: 45px; height: 150px; color: white">
					<div style="text-align: right; width: 100%; padding-right: 0.5vw; padding-top: 0.5vw">
						<a href="" class="btn"><img src="/images/add_white.png" alt="+" height="25vw"></a>
					</div>
					<div style="position: absolute; bottom: 0; padding-left: 1vw; padding-bottom: 0.75vw; color:white; font-size: x-large">Mes rendez-vous</div>
				</div>
				<div class="pave" style=" height: 300px; background-image: url('/images/pro_pave_communaute.jpg'); background-size: cover">
					<div style="text-align: right; width: 100%; padding-right: 0.5vw; padding-top: 0.5vw">
						<a href="" class="btn"><img src="/images/add_red.png" alt="+" height="25vw"></a>
					</div>
					<div style="position: absolute; bottom: 0; padding-left: 1vw; padding-bottom: 0.75vw; font-size: x-large; text-align: left; color: white; ">Communauté des praticiens Capsule</div>
				</div>
			</div>
		</div>

		<div style="background-image: url('/images/pro_home_event.jpg'); background-size: 100%; background-repeat: no-repeat; width: 100%; margin-bottom: 2vh; padding-left: 55%; padding-right: 4%">
			<h1 style="padding-top: 25%; padding-bottom: 10%; font-variant-caps: small-caps">Evénements Capsule</h1>
			<p style="padding-bottom: 10%">Parce que Capsule c’est aussi un espace d’échange, découvrez les prochaines dates de nos événements digitaux & conférences, et réservez votre place en tant que participant ou en tant que speaker</p>
			<div>
				<a href="" type="button" class="btn" style="margin-bottom: 3vh; background-color: rgba(48, 180, 167, 1); color: white; font-size: x-large">En savoir +</a>
			</div>
		</div>
		{# {{ dump(user)}} #}
	</div>
{% endblock %}

templates/pro/messages.html.twig
{% extends "base-js.html.twig" %}

{% block body %}
	<div class="mx-auto py-8 px-10">
		<div {{ react_component('App', { userObj: userJson, userRole: role }) }}></div>
	</div>
{% endblock %}

templates/pro/navbar.html.twig
{% extends "base.html.twig" %}
{% block title %}
	Capsule - Pro
{% endblock %}

{# barre de navigation #}
{% block navbar %}

	<nav class="navbar navbar-expand-sm sticky-top" style="padding: 0; background: rgb(255,237,121);">
		<div class="container-fluid">
			<a class="navbar-brand" href="/"><img src="/images/Logo.png" alt="Logo Capsule" width="40" height="48.2"></a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarSupportedContent" style="width: 100%">
				<div class="navbar-nav" style="width: 100%">
					<a class="nav-link active" aria-current="page" href="/pro/home">Accueil</a>
					<a class="nav-link active" aria-current="page" href="/pro/patients">Patients</a>
					<a class="nav-link active" aria-current="page" href="/pro/agenda">Agenda</a>
					<a class="nav-link" aria-current="page" href="#" onmouseover="Coming soon">Messages</a>
					<a class="nav-link active" aria-current="page" href="#">Bloc note</a>
					<a class="nav-link active" aria-current="page" href="#">Capsule TV</a>
					<a data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample" class="btn">{{user.firstName}}
						{{user.name}}</a>

				</div>
			</div>
		</div>
	</nav>
{% endblock %}

{% block body %}
	{% block content %}{% endblock %}
{% endblock %}

templates/pro/new.html.twig
{% extends "pro/navbar.html.twig" %}

{% block body %}
	<h1>Dossier de candidature</h1>
	<div class="container text-center">
		<form method="POST" enctype="multipart/form-data">
			<input type="hidden" name="role" value="pro">
			<fieldset>
				<legend>Identité</legend>
				<div class="row row-col-1 row-cols-sm-3">
					<div class="col">
						<input type="hidden" name="MAX_FILE_SIZE" value="1100000"/>
						<input type="file" name="pic" accept="image/png, image/jpg, image/jpeg, image/gif, image/svg">
					</div>
					<div class="col">
						<p>
							<label for="title">Titre de civilité :</label>
							<select id="title" name="title">
								<option value="Mme">Madame</option>
								<option value="Mr">Monsieur</option>
								<option value="Dr">Docteur</option>
								<option value="Pr">Professeur</option>
							</select>
						</p>
						<p><input type="text" name="name" placeholder="Nom *" required></p>
						<p><input type="text" name="first_name" placeholder="Prénom" required></p>
						<p><input type="tel" name="phone_office" placeholder="Téléphone professionnel *" required></p>
						<p><input type="tel" name="phone_mobile" placeholder="Téléphone mobile"></p>
					</div>
					<div class="col">
						<p><input type="text" name="street1" placeholder="N° et rue"></p>
						<p><input type="text" name="street2" placeholder="Complément"></p>
						<p><input type="text" name="postcode" placeholder="Code postal"></p>
						<p><input type="text" name="city" placeholder="Ville"></p>
						<p><input type="email" name="email" placeholder="Email *" required></p>
					</div>
				</div>
			</fieldset>
			<fieldset>
				<legend>Formation</legend>
				<input type="hidden" name="educations" value="3" id="educations">
				<p><input type="date" name="date1" style="margin-right: 25px" required>
					<input type="text" name="degree1" placeholder="Diplôme ou titre obtenu *" size="54" style="margin-right: 25px" required>
					<input type="text" name="school1" placeholder="Ecole ou organisme certificateur *" size="54" required></p>
				<p><input type="date" name="date2" style="margin-right: 25px">
					<input type="text" name="degree2" placeholder="Diplôme ou titre obtenu" size="54" style="margin-right: 25px">
					<input type="text" name="school2" placeholder="Ecole ou organisme certificateur" size="54"></p>
				<p><input type="date" name="date3" style="margin-right: 25px">
					<input type="text" name="degree3" placeholder="Diplôme ou titre obtenu" size="54" style="margin-right: 25px">
					<input type="text" name="school3" placeholder="Ecole ou organisme certificateur" size="54"></p>
			</fieldset>
			<fieldset>
				<input type="hidden" name="experiences" value="3" id="experiences">
				<legend>Expérience</legend>
				<p><input type="date" name="dateStart1" style="margin-right: 25px" required>
					<input type="date" name="dateEnd1" style="margin-right: 25px">
					<input type="text" name="position1" placeholder="Poste* " size="45" style="margin-right: 25px" required>
					<input type="text" name="employer1" placeholder="Employeur *" size="45" required></p>
				<p><input type="date" name="dateStart2" style="margin-right: 25px">
					<input type="date" name="dateEnd2" style="margin-right: 25px">
					<input type="text" name="position2" placeholder="Poste" size="45" style="margin-right: 25px">
					<input type="text" name="employer2" placeholder="Employeur" size="45"></p>
				<p><input type="date" name="dateStart3" style="margin-right: 25px">
					<input type="date" name="dateEnd3" style="margin-right: 25px">
					<input type="text" name="position3" placeholder="Poste" size="45" style="margin-right: 25px">
					<input type="text" name="employer3" placeholder="Employeur" size="45"></p>
			</fieldset>

			<fieldset>
				<input type="hidden" name="experiences" value="3" id="experiences">
				<legend>Profession et spécialités</legend>
				<div class="row row-col-1 row-cols-sm-2" style="padding-bottom: 10px">
					<div class="col">
						Profession :<br>
						<input list="profession">
						<datalist id="profession" name="profession">
							<option value="Psychiatre">Psychiatre</option>
							<option value="Psychologue">Psychologue</option>
							<option value="Coach">Coach</option>
							<option value="Sage-femme">Sage-femme</option>
							<option value="Gynécologue">Gynécologue</option>
						</datalist>
					</div>
					<div class="col">
						Sélection spécialités :<br>
						<div style="max-height: 100px; overflow: auto">
							<input type="checkbox" name="specialty1" value="1">
							<label for="specialty1">
								Confiance en soi</label><br>
							<input type="checkbox" name="specialty2" value="2">
							<label for="specialty2">
								Addiction</label><br>
							<input type="checkbox" name="specialty3" value="3">
							<label for="specialty3">
								Gestion du stress</label><br>
							<input type="checkbox" name="specialty4" value="4">
							<label for="specialty4">
								Optimiser les apprentissages</label><br>
							<input type="checkbox" name="specialty5" value="5">
							<label for="specialty5">
								Gérer les relations aux autres</label><br>
							<input type="checkbox" name="specialty6" value="6">
							<label for="specialty6">
								Nutrition</label>
						</div>
					</div>
				</div>
			</fieldset>
			<fieldset>
				<legend>Présentation<br>
					<textarea name="bio" cols="110vw" rows="5" style="font-size: 0.75em"></textarea>
				</legend>
			</fieldset>

			<p><input type="submit" value="Soumettre">
			</p>
		</form>
	</div>
</div>{% endblock %}{% block javascript %}
<script>
	function changeValues(field) {
var element = document.getElementById(field)
element.value = element.value + 1
}
</script>{% endblock %}

templates/pro/profil.html.twig
{% extends "base-js.html.twig" %}

{% block body %}
	<div class="container" style="margin-bottom: 30px">
		<h1 style="margin: 25px 0">{{ user.firstName}}
			{{ user.name}}</h1>


		<div class="row">
			<button class="btn btn-dark" style="width: 200px; margin: auto; background: white; color: black; border: 1px solid rgb(255,237,121)" onclick="reveal('infos')">Infos</button>
			<button class="btn btn-dark" style="width: 200px; margin: auto; background: white; color: black; border: 1px solid rgb(255,237,121)" onclick="reveal('interest')">Centres d'intérêts</button>
			<button class="btn btn-dark" style="width: 200px; margin: auto; background: white; color: black; border: 1px solid rgb(255,237,121)" onclick="reveal('services')">Prestations</button>
			<button class="btn btn-dark" style="width: 200px; margin: auto; background: white; color: black; border: 1px solid rgb(255,237,121)" onclick="reveal('hours')">Horaires</button>
			<button class="btn btn-dark" style="width: 200px; margin: auto; background: white; color: black; border: 1px solid rgb(255,237,121)" onclick="reveal('payments')">Moyens de paiement</button>
		</div>
		<div class="row" id="infos" style"display: block; margin: 15px 0">
			{{ dump(user.profilePic)}}<br>
			<p>{{ user.email }}<br>
				{{ user.phoneMobile}}</p>
		</div>
		<div class="row" id="interest" style="display: none; margin: 15px 0">Interest</div>
		<div class="row" id="services" style="display: none; margin: 15px 0">services</div>
		<div class="row" id="hours" style="display: none; margin: 15px 0">
			<div class="container">
				<form method="post">
					<table style="width: 80%; margin: 20px auto">
						<tr>
							<th style="width: 12.5%"></th>
							<th style="width: 12.5%">Lundi</th>
							<th style="width: 12.5%">Mardi</th>
							<th style="width: 12.5%">Mercredi</th>
							<th style="width: 12.5%">Jeudi</th>
							<th style="width: 12.5%">Vendredi</th>
							<th style="width: 12.5%">Samedi</th>
							<th style="width: 12.5%">Dimanche</th>
						</tr>
						<tr>
							<td></td>
							<td><input type="checkbox" name="lundi"></td>
							<td><input type="checkbox" name="mardi"></td>
							<td><input type="checkbox" name="mercredi"></td>
							<td><input type="checkbox" name="jeudi"></td>
							<td><input type="checkbox" name="vendredi"></td>
							<td><input type="checkbox" name="samedi"></td>
							<td><input type="checkbox" name="dimanche"></td>
						</tr>
						<tr>
							<td rowspan="2">Matin</td>
							<td style="padding: 10px 0 0 0"><input type="time" name="start_am_lundi" id=""></td>
							<td style="padding: 10px 0 0 0"><input type="time" name="start_am_mardi" id=""></td>
							<td style="padding: 10px 0 0 0"><input type="time" name="start_am_mercredi" id=""></td>
							<td style="padding: 10px 0 0 0"><input type="time" name="start_am_jeudi" id=""></td>
							<td style="padding: 10px 0 0 0"><input type="time" name="start_am_vendredi" id=""></td>
							<td style="padding: 10px 0 0 0"><input type="time" name="start_am_samedi" id=""></td>
							<td style="padding: 10px 0 0 0"><input type="time" name="start_am_dimanche" id=""></td>
						</tr>
						<tr>
							<td><input type="time" name="end_am_lundi" id=""></td>
							<td><input type="time" name="end_am_mardi" id=""></td>
							<td><input type="time" name="end_am_mercredi" id=""></td>
							<td><input type="time" name="end_am_jeudi" id=""></td>
							<td><input type="time" name="end_am_vendredi" id=""></td>
							<td><input type="time" name="end_am_samedi" id=""></td>
							<td><input type="time" name="end_am_dimanche" id=""></td>
						</tr>
						<tr>
							<td rowspan="2">Après-midi</td>
							<td style="padding: 10px 0 0 0"><input type="time" name="start_pm_lundi" id=""></td>
							<td style="padding: 10px 0 0 0"><input type="time" name="start_pm_mardi" id=""></td>
							<td style="padding: 10px 0 0 0"><input type="time" name="start_pm_mercredi" id=""></td>
							<td style="padding: 10px 0 0 0"><input type="time" name="start_pm_jeudi" id=""></td>
							<td style="padding: 10px 0 0 0"><input type="time" name="start_pm_vendredi" id=""></td>
							<td style="padding: 10px 0 0 0"><input type="time" name="start_pm_samedi" id=""></td>
							<td style="padding: 10px 0 0 0"><input type="time" name="start_pm_dimanche" id=""></td>
						</tr>
						<tr>
							<td><input type="time" name="end_pm_lundi" id=""></td>
							<td><input type="time" name="end_pm_mardi" id=""></td>
							<td><input type="time" name="end_pm_mercredi" id=""></td>
							<td><input type="time" name="end_pm_jeudi" id=""></td>
							<td><input type="time" name="end_pm_vendredi" id=""></td>
							<td><input type="time" name="end_pm_samedi" id=""></td>
							<td><input type="time" name="end_pm_dimanche" id=""></td>
						</tr>
						<tr>
							<td></td>
							<td style="padding: 10px 0 0 0" colspan="2">Durée d'un créneau</td>
							<td style="padding: 10px 0 0 0"><input type="time" name="duration" id=""></td>
							<td style="padding: 10px 0 0 0" colspan="2">Pause</td>
							<td style="padding: 10px 0 0 0"><input type="time" name="pause" id=""></td>
							<td></td>
						</tr>
					</table>
					<input type="submit" value="Enregistrer">

				</form>


			</div>
		</div>
		<div class="row" id="payments" style="display: none; margin: 15px 0">payments</div>
	</div>
{% endblock %}
{% block script %}
	<script>
		function reveal(div) {
let d1 = document.getElementById("infos");
let d2 = document.getElementById("interest");
let d3 = document.getElementById("services");
let d4 = document.getElementById("hours");
let d5 = document.getElementById("payments");
d1.style.display = "none";
d2.style.display = "none";
d3.style.display = "none";
d4.style.display = "none";
d5.style.display = "none";
let d = document.getElementById(div);
d.style.display = "block";
}
	</script>
{% endblock %}